name: Push

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions: read-all

jobs:
  release:
    permissions:
      contents: write
    uses: quike/workflow-github/.github/workflows/release.yml@15a6f8baec0dea98eb96de5766c595404ae3424d # v1.88
    secrets: inherit

  build:
    runs-on: ubuntu-24.04
    name: Build
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Verify
        run: |
          echo "release-published: ${{ needs.release.outputs.release-published }}"
          echo "release-version: ${{ needs.release.outputs.release-version }}"
          echo "release-major: ${{ needs.release.outputs.release-major }}"
          echo "release-minor: ${{ needs.release.outputs.release-minor }}"
          echo "release-patch: ${{ needs.release.outputs.release-patch }}"
          echo "release-type: ${{ needs.release.outputs.release-type }}"
          echo "release-git-head: ${{ needs.release.outputs.release-git-head }}"
          echo "release-git-tag: ${{ needs.release.outputs.release-git-tag }}"
      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          distribution: "temurin"
          java-version: "23"
      - name: Cache Maven packages
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Build
        run: |
          ./mvnw spotless:check verify -B -Drevision=${{ needs.release.outputs.release-version }}
